POST http://localhost:3000/auth/login
content-type: application/json

{
    "phone": "123",
    "password": "hashme2"
}


### request without header

GET http://localhost:3000/auth/home
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInBob25lIjoiMTIzIiwiaWF0IjoxNzI0MDUzMTQzLCJleHAiOjE3MjQwNTY3NDN9.PKsYCQbICbPkoPAi-Tv75kst1HGQWg-S5OTMMURQN_I